### ISSUE TITLE
The boolean conditions doesn't seem to work in v0.15.24

### ISSUE THREAD

**Issue by martinmicunda** [systemjs/builder#657] opened 2016-07-27 10:41 UTC
Hi,

I have upgraded my `jspm` to `v0.17.0-beta.24` which contains `systemjs-builder v0.15.24` and boolean conditions doesn't seem to work.

*src/app/shared/config/env.conditions.js*
```js
export var mock = false;
export var optimize = false;
export var environment = 'prod';
```

*Gulp builder task*

```js
gulp.task('bundle', ['jshint'], (cb) => {
    const env = utils.getEnv().toLowerCase();
    const Builder = require('jspm/node_modules/systemjs-builder');
    const builder = new Builder('.', `${path.jspm.config}`);
    const inputPath = `${path.jspm.mainModule}`;
    const outputFile = `${path.tmp.scripts}build.js`;
    const outputOptions = {
        sourceMaps: true,
        config: {sourceRoot: path.tmp.scripts},
        conditions: {
            'src/app/shared/config/env.conditions.js|mock': env === 'test', // this doesn't work
            'src/app/shared/config/env.conditions.js|environment': env // this works
        }
    };

    builder.buildStatic(inputPath, outputFile, outputOptions)
        .then(() => cb())
        .catch((ex) => cb(new Error(ex)));
});
```

When env flag is set to false it should not load the `users.resource.mock.js` file however in `systemjs-builder v0.15.24` it does load this file. 

```js
import './users.resource.mock.js#?conditions|mock';
```

The issue is only with boolean conditions as other conditions (e.g. below) works fine:

```js
import './config.#{conditions|environment}.js';
```

**Comment by guybedford** [comment] 2016-07-27 11:40
What is the error that you are getting here? Unable to resolve exact conditional?

**Comment by martinmicunda** [comment] 2016-07-27 11:49
There is no error... But it always import the file even when the flag is set to false. Basically when the flag is set to false it should not load the file...

Sent from my iPhone

On 27 Jul 2016, at 12:41, Guy Bedford <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the error that you are getting here? Unable to resolve exact conditional?

-

**Comment by guybedford** [comment] 2016-07-27 11:54
If you're doing a static build and it isn't giving an error then it is resolving the conditional then though? Because static builds will never contain `#` in the output module names.

So is the issue that you just don't want it to trace the `conditions|mock` condition module at all, or you don't want it to load the `users.resource.mock.js` file at all during the build?

**Comment by martinmicunda** [comment] 2016-07-27 12:00
I don't want to load the users.resource.mock.js file as this file contains testing specific code that I don't want to have in production but for some reason this file is always loaded even when flag is set to false ...

Sent from my iPhone

On 27 Jul 2016, at 12:54, Guy Bedford <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're doing a static build and it isn't giving an error then it is resolving the conditional then though? Because static builds will never contain # in the output module names.

So is the issue that you just don't want it to trace the conditions|mock condition module at all, or you don't want it to load the users.resource.mock.js file at all during the build?

-

**Comment by guybedford** [comment] 2016-07-27 12:02
I see, thanks I will look into it.

**Comment by guybedford** [comment] 2016-08-01 11:08
@martinmicunda I think we previously added a test case for exactly this in https://github.com/systemjs/builder/blob/master/test/fixtures/conditional-tree/custom-conditions.js. `mock.js` has a console.log statement to indicate execution, which I can confirm isn't running during the tests at all when traced with false.

I can't see that the test there is any different to the replication you've described, unless this is some fine detail to do with the normalization process itself?

**Comment by martinmicunda** [comment] 2016-08-01 11:11
I will double check that tomorrow morning and will let you know ... Thanks a lot

**Comment by guybedford** [comment] 2016-09-26 14:15
Closing as I believe this is working, but please let me know if there is still an issue here.

**Closed by guybedford** 2016-09-26 14:15 UTC
