### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by SerkanSipahi** [systemjs/builder#318] opened 2015-09-21 08:34 UTC
Im using jspm for bundling an app but i think this is a system-builder problem because it throw an error if i use following command:  ` jspm bundle src/main dist/bundle.js --inject `

```shell
TypeError: Cannot read property 'substr' of undefined
         at Trace.getLoadRecord (/Users/serkansipahi/node_modules/systemjs-builder/lib/trace.js:69:16)
         at Trace.getAllLoadRecords (/Users/serkansipahi/node_modules/systemjs-builder/lib/trace.js:379:15)
         at /Users/serkansipahi/node_modules/systemjs-builder/lib/trace.js:389:21
         at Array.map (native)
         at /Users/serkansipahinode_modules/systemjs-builder/lib/trace.js:388:96
         at process._tickCallback (node.js:356:9)
```

The strange thing is the error occurs if i use a method in a ES6 class ( see below core.js ) but if i remove the method and just use only a constructor in the class, jspm(system-bulider) can bundle the app.  

console.log('getLoadRecord', canonical); on [ line for systemjs-builder/lib/trace:69 ](https://github.com/systemjs/builder/blob/master/lib/trace.js#L65) produce that:

```shell
getLoadRecord src/main.js
getLoadRecord src/app.js
getLoadRecord src/core.js
getLoadRecord npm:babel-runtime@5.8.24/helpers/create-class
getLoadRecord npm:babel-runtime@5.8.24/helpers/class-call-check
getLoadRecord npm:babel-runtime@5.8.24/core-js/object/define-property
getLoadRecord undefined
```

@guybedford : whats going wrong?

// package.json
```json
{
  "name": "....",
  "version": "1.0.0",
  "description": "...",
  "main": "index.js",
  "scripts": {
    "test": "test"
  },
  "author": "Serkan Sipahi <serkan.sipahi@yahoo.de>",
  "license": "ISC",
  "dependencies": {
    "jspm": "^0.16.6"
  },
  "jspm": {
    "dependencies": {},
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  }
}

```

```js

// config.js
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "stage": 0,
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  map: {
    "babel": "npm:babel-core@5.8.25",
    "babel-runtime": "npm:babel-runtime@5.8.24",
    "core-js": "npm:core-js@1.1.4",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@5.8.24": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@1.1.4": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});


```

```js

// main.js
import { app } from './app';
app();

```

```js

// app.js
import { Core } from './core';
export function app(){
	new Core();
}

```

```js

//core.js
class Core {

	constructor() {
		console.log('Core.constructor()');
	}

	foo() {
		console.log('Core.foo()');
	}

}

export { Core };


```

**Comment by guybedford** [comment] 2015-09-21 12:57
Thanks this does look like a duplicate of https://github.com/systemjs/builder/issues/317.

**Closed by guybedford** 2015-09-21 12:57 UTC
