### ISSUE TITLE
Weird issue with a simple plugin

### ISSUE THREAD

**Issue by tbranyen** [systemjs/builder#22] opened 2014-11-09 01:59 UTC
I've created a very simple plugin that compiles Lo-Dash templates:

``` javascript
import _ from 'underscore';

export function translate(load) {
  return 'module.exports = ' + _.template(load.source).source + ';';
}
```

I manually set the path:

``` javascript
module.exports = function(grunt) {
    var local = path.join.bind(path, __dirname);
    var done = this.async();

    builder.build('src/main', {
      baseURL: local('../'),

      paths: {
        underscore: 'node_modules/lodash/dist/lodash.js',
        tmpl: 'src/plugins/lodash.js'
      }
    }, local('../prod/app.js'))
    .then(done).catch(done);
};
```

I get the error:

``` sh
Warning: Execution must define a Module instance Use --force to continue.
```

So I commented out the inclusion of lodash in my plugin and then it "works" although, I have to return an empty string... which is not ideal.  Any idea on how I can fix this.

I'll update the issue if I figure it out.

**Comment by victorwpbastos** [comment] 2015-01-12 20:25
I'm having the same problem:

```js
var Ractive = require('ractive');

exports.instantiate = function(load) {
	return Ractive.parse(load.source); 
}
```

This code in `runtime` runs fine but in `bundle` returns:

`Execution must define a Module instance`

**Comment by guybedford** [comment] 2015-01-13 09:56
@victorwpbastos this is because you need to use the `translate` hook. If using the `instantiate` hook, you need to return a special instantiate result object (https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader), so it is advisable not to use that hook.

Rather try something like:

```javascript
var Ractive = require('ractive');

exports.translate = function(load) {
    return 'module.exports = ' + JSON.stringify(Ractive.parse(load.source));
}
```

Or if you really want to use `instantiate`:

```javascript
var Ractive = require('ractive');

exports.instantiate = function(load) {
  return {
    deps: [],
    execute: function() {
      return Ractive.parse(load.source);
    }
  };
}
```

**Comment by guybedford** [comment] 2015-01-13 09:56
Note the other benefit of using `translate` is that the plugin will support building through this builder, while only using instantiate means it will only work for browser loading.

**Comment by victorwpbastos** [comment] 2015-01-13 14:25
I did follow your suggestion but the error continues. In runtime is ok but `jspm bundle` returns `Execution must define a Module instance`.

**Comment by guybedford** [comment] 2015-01-13 14:33
And you're definitely using the `translate` hook above?

**Comment by victorwpbastos** [comment] 2015-01-13 14:40
yes. I think the problem is with the `require('ractive')` line. When the plugin don't `require` anything it works. In this case I need `ractive`. This is the full error:
![capturar](https://cloud.githubusercontent.com/assets/1017515/5722199/529aca0a-9b21-11e4-984d-069a7755fd26.PNG)

**Comment by guybedford** [comment] 2015-01-13 14:46
@victorwpbastos try installing `npm:ractive` instead.

**Comment by guybedford** [comment] 2015-01-13 14:47
Basically the issue is with the plugin compiler code not working in Node. This is probably @tbranyen's issue with loading underscore as well, which would probably also be fixed with `npm:underscore` under the latest jspm (10.4).

**Comment by victorwpbastos** [comment] 2015-01-13 14:51
It works! I think you right, maybe is a issue with Ractive. Off topic: I saw your jsconf talk in youtube yesterday and I like your sublime colour scheme. Which one is that?

**Comment by guybedford** [comment] 2015-01-13 15:11
Yes the browser build on GitHub is not designed to work in Node.

Sure - I think it's LAZY.

**Comment by guybedford** [comment] 2015-01-13 15:11
I think we've actually resolved this issue all around - I'm closing for now, @tbranyen let me know if you need further support on this at all, I'm pretty confident you'll find it works with the latest jspm.

**Closed by guybedford** 2015-01-13 15:11 UTC

**Comment by emirotin** [comment] 2015-03-19 10:59
I have the same problem with https://github.com/forresto/plugin-coffee

**Comment by guybedford** [comment] 2015-03-20 11:39
@emirotin can you post the details to the Coffee plugin page - this sounds like it could be an issue with the CoffeeScript plugin.

Note also that you must write `return "module.exports = " + JSON.stringify(Ractive.parse(load.source)) + ";";`` in the translate hook.

**Comment by emirotin** [comment] 2015-03-20 11:42
> Note also that you must write return "module.exports = " + JSON.stringify(Ractive.parse(load.source)) + ";";` in the translate hook.

exactly what I did, works with npm:ractive but not with github:ractivejs/ractive

> can you post the details to the Coffee plugin page
yeah, but it's probably the same described in the thread — something in the built coffee-script.js used there doesn't work in Node.js, while using "normal" CoffeeScript (installed with jspm) doesn't work in the browser because it relies on child_process which throws in that case
