### ISSUE TITLE
separateCSS option does not work with bundle arithmetic.

### ISSUE THREAD

**Issue by mikol** [systemjs/builder#220] opened 2015-07-06 23:41 UTC
For example, consider `builder.build('main + a.css + b.css', 'out.js')` with `builder.config({ separateCSS: true })`. If `main` further depends on `c.css`, we would expect `out.css` to contain `a.css`, `b.css`, and `c.css`. What `out.css` actually contains is only `c.css`.

I believe this is due to two factors. First, [the `metadata.bundle` check in `traceModule`](https://github.com/systemjs/builder/blob/master/lib/builder.js#L337-L346) doesn’t extract the right components from the bundle equation so `a.css` and `b.css` are never included in the bundle. If this check is commented out and the code simply falls through to the current `else` block, then `a.css` and `b.css` will be handed off to the CSS plugin for processing.

However, this is where the second factor comes in. The CSS plugin will process `a.css` and `b.css` together, but `c.css` is handled separately. The result is that `c.css` overwrites the existing `a.css + b.css` bundle and therefore `out.css` again only contains `c.css`.

**Comment by guybedford** [comment] 2015-07-08 16:31
Are you configuring the CSS files to use the CSS loader here? If not then they definitely won't build.

With loader-by-default configuration (`System.config({ meta: { '*.css': { loader: 'css' } } })`) this should work though.

In future all loaders will be config based through packages config making this work out in due course.

Just let me know if you have any further questions.

**Comment by mikol** [comment] 2015-07-08 20:48
Sorry for the omission in my report, the arithmetic is: `builder.build('main + a.css! + b.css!', 'out.js')`, which I believe is equivalent to configuring the loader (which I haven’t done.)

Note that if I omit the `separateCSS` option, the CSS files end up inlined in the bundle as expected.

**Comment by guybedford** [comment] 2015-07-09 11:06
Ah right ok, this may be a bug then.

**Comment by guybedford** [comment] 2015-07-12 17:26
Ok I've created a test repo at https://github.com/guybedford/separate-css-test.

`npm install && jspm install && node task`

Seems to work fine for me. Perhaps see if you can have a look at it and match it up to the breaking scenario you found?

**Comment by guybedford** [comment] 2015-07-28 11:53
Closing due to not being able to replicate. Further help reproducing welcome.

**Closed by guybedford** 2015-07-28 11:53 UTC
