### ISSUE TITLE
Unhandled exception when fail to resolve canonical name.

### ISSUE THREAD

**Issue by MeoMix** [systemjs/builder#317] opened 2015-09-19 23:50 UTC
Hey,

Latest version introduced a regression in displaying an error message when canonical name cannot be resolved.

Trace.getLoadRecord is passed undefined which causes an exception. It's given undefined because the canonical name was unable to be found for a given module.

![untitled](https://cloud.githubusercontent.com/assets/1380995/9978603/6b0c5ef0-5eee-11e5-9d18-f0ed3739648b.png)

**Comment by SerkanSipahi** [comment] 2015-09-21 11:46
@MeoMix i get the same error: see https://github.com/systemjs/builder/issues/318 : well documented when it happens !

**Comment by guybedford** [comment] 2015-09-21 13:43
@SerkanSipahi thanks for the test case - I tried your example from #318, and got the correct output:

```
jspm bundle src/main dist/bundle.js --inject
     Building the bundle tree for src/main...
     
       npm:babel-runtime@5.8.24/core-js/object/define-property
       npm:babel-runtime@5.8.24/helpers/class-call-check
       npm:babel-runtime@5.8.24/helpers/create-class
       npm:core-js@1.1.4/library/fn/object/define-property
       npm:core-js@1.1.4/library/modules/$
       src/app.js
       src/core.js
       src/main.js
     
ok   dist/bundle.js added to config bundles.
ok   Built into dist/bundle.js with source maps, unminified.
```

Are you sure you are running on the latest jspm 0.16.6? Any help with replication here is appreciated.

**Comment by SerkanSipahi** [comment] 2015-09-21 19:49
yes sure (jspm v0.16.6), see my package.json

```json
{
  "name": "...",
  "version": "1.0.0",
  "description": "...",
  "main": "index.js",
  "scripts": {
    "test": "test"
  },
  "author": "Serkan Sipahi <serkan.sipahi@yahoo.de>",
  "license": "ISC",
  "dependencies": {
    "jspm": "^0.16.6"
  },
  "jspm": {
    "dependencies": {},
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  }
}

```
further more see:

`/Users/serkansipahi/node_modules/jspm/package.json`
```json
{
  "_args": [
    [
      "jspm@^0.16.6",
      "/Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/extension-youtube"
    ]
  ],
  "_from": "jspm@>=0.16.6 <0.17.0",
  "_id": "jspm@0.16.6",
  "_inCache": true,
  "_location": "/jspm",
  "_nodeVersion": "0.12.7",
  "_npmUser": {
    "email": "guybedford@gmail.com",
    "name": "guybedford"
  },
  "_npmVersion": "2.11.3",
  "_phantomChildren": {},
  "_requested": {
    "name": "jspm",
    "raw": "jspm@^0.16.6",
    "rawSpec": "^0.16.6",
    "scope": null,
    "spec": ">=0.16.6 <0.17.0",
    "type": "range"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/jspm/-/jspm-0.16.6.tgz",
  "_shasum": "904fc5c52d193350f9b61e9f6026a2ed81185b8c",
  "_shrinkwrap": null,
  "_spec": "jspm@^0.16.6",
  "_where": "/Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/extension-youtube",
  "author": "",
  "bin": {
    "jspm": "./jspm.js"
  },
  "bugs": {
    "url": "https://github.com/jspm/jspm/issues"
  },
  "dependencies": {
    "chalk": "^1.0.0",
    "core-js": "^0.9.17",
    "glob": "^5.0.10",
    "graceful-fs": "^3.0.8",
    "jspm-github": "^0.13.3",
    "jspm-npm": "^0.25.0",
    "jspm-registry": "^0.4.0",
    "liftoff": "^2.1.0",
    "minimatch": "^2.0.8",
    "mkdirp": "~0.5.1",
    "ncp": "^2.0.0",
    "request": "^2.58.0",
    "rimraf": "^2.4.0",
    "rsvp": "^3.0.18",
    "semver": "^5.0.1",
    "systemjs": "0.19.0",
    "systemjs-builder": "0.14.3",
    "traceur": "0.0.91",
    "uglify-js": "~2.4.23"
  },
  "description": "Registry and format agnostic JavaScript package manager",
  "devDependencies": {
    "istanbul": "^0.3.13",
    "jshint": "~2.8.0",
    "mocha": "~2.2.5"
  },
  "directories": {
    "test": "test"
  },
  "dist": {
    "shasum": "904fc5c52d193350f9b61e9f6026a2ed81185b8c",
    "tarball": "http://registry.npmjs.org/jspm/-/jspm-0.16.6.tgz"
  },
  "gitHead": "3e7ec881b4bcfeb46388f9218e5612b0f2203832",
  "homepage": "https://github.com/jspm/jspm",
  "ignore": [
    "sandbox",
    "test",
    "testlibs"
  ],
  "installable": true,
  "license": "Apache 2.0",
  "main": "./api.js",
  "maintainers": [
    {
      "name": "guybedford",
      "email": "guybedford@gmail.com"
    }
  ],
  "name": "jspm",
  "optionalDependencies": {},
  "registry": "npm",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jspm/jspm.git"
  },
  "scripts": {
    "coverage": "npm run istanbul -- --report html",
    "istanbul": "istanbul cover ./node_modules/.bin/_mocha -i='lib/**/*.js'",
    "jshint": "jshint api.js cli.js jspm.js lib test",
    "mocha": "mocha",
    "test": "npm run jshint && npm run mocha"
  },
  "version": "0.16.6"
}

```

// System, Tools
`MacOS v10.10.1`
`iojs v3.2.0`
`npm v3.3.1`

**Comment by SerkanSipahi** [comment] 2015-09-21 20:21
I upgrade nodejs to v4.1.0 and npm to stable 2.14.3 . Nothing has changed.

**Comment by guybedford** [comment] 2015-09-21 20:26
@SerkanSipahi perhaps you can share a git repo that reproduces this?

**Comment by SerkanSipahi** [comment] 2015-09-21 20:37
@guybedford the repo with all installed( node_modules, jspm_packages ) dependencies? or just classic repo with package.json and app src files, etc. I think for reproducing its better with installed node_modules and jspm_packages. ok?

**Comment by guybedford** [comment] 2015-09-21 20:37
Sure, that works.

**Comment by SerkanSipahi** [comment] 2015-09-21 21:07
it took some time with the upload, so now ready, see -> https://github.com/SerkanSipahi/test-repo-jspm

**Comment by SerkanSipahi** [comment] 2015-09-22 07:02
@can you share your repo( package.json and src files ) , thanks.

**Comment by SerkanSipahi** [comment] 2015-09-22 17:53
@guybedford which node version do you use?

**Comment by SerkanSipahi** [comment] 2015-09-22 18:59
@guybedford : something goes wrong on my env (?!?mac,node,npm?!?) :( this is totally annoying!!

`jspm bundle src/main dist/bundle.js --inject`
```
jspm v0.16.6 -> err  TypeError: Cannot read property 'substr' of undefined
jspm v0.16.5 -> err  TypeError: Cannot read property 'substr' of undefined
jspm v0.16.4 -> err  TypeError: Cannot read property 'substr' of undefined
jspm v0.16.3 -> err  Error: ENOENT: no such file or directory, open '/Users/serkansipahi/jspm_packages/.dependencies.json'
jspm v0.16.2 -> err  TypeError: Cannot read property 'substr' of undefined
jspm v0.16.1 -> err  TypeError: Cannot read property 'substr' of undefined
jspm v0.16.0 -> err  TypeError: Cannot read property 'substr' of undefined
jspm v0.15.7 -> err  Error: Error loading "node_modules/core-js/library/fn/object/define-property" at file:/Users/serkansipahi/node_modules/core-js/library/fn/object/define-property.js
jspm v0.15.6 -> err  Error: Error loading "node_modules/core-js/library/fn/object/define-property" at file:/Users/serkansipahi/node_modules/core-js/library/fn/object/define-property.js
jspm v0.15.5 -> err  Error: Error loading "node_modules/core-js/library/fn/object/define-property" at file:/Users/serkansipahi/node_modules/core-js/library/fn/object/define-property.js
jspm v0.15.4 -> err  Error: Error loading "node_modules/core-js/library/fn/object/define-property" at file:/Users/serkansipahi/node_modules/core-js/library/fn/object/define-property.js
jspm v0.15.3 -> err  Error: Error loading "node_modules/core-js/library/fn/object/define-property" at file:/Users/serkansipahi/node_modules/core-js/library/fn/object/define-property.js
jspm v0.15.2 -> err  Error: Error loading "node_modules/core-js/library/fn/object/define-property" at file:/Users/serkansipahi/node_modules/core-js/library/fn/object/define-property.js
jspm v0.15.1 -> ok   Built into dist/bundle.js with source maps, unminified.
jspm v0.15.0 -> ok   Built into dist/bundle.js with source maps, unminified.
```

**Comment by guybedford** [comment] 2015-09-22 19:00
@SerkanSipahi are you using jspm_packages or node_modules? I tried the test case but couldn't get it to work unfortunately.

**Comment by SerkanSipahi** [comment] 2015-09-22 19:13
@guybedford what do you mean with jspm_packages or node_modules?

Info: Im using jspm for 6 month, systemjs, system-builder over 1 year at "work/company" but at home on my mac will work nothing :(

**Comment by guybedford** [comment] 2015-09-22 19:16
@SerkanSipahi your paths in the errors above are calling into node_modules, which will not easily load through jspm without manual package configurations. Your environment seems to have quite a bit going on, I can't help without a specific issue to look at. I'm certainly looking into the canonical issue now though.

**Comment by SerkanSipahi** [comment] 2015-09-22 19:33
I know it was just a reporting for you. I need jspm greater than or equal v0.16.0. Can i help you? What does canonical? For what is it?

**Comment by guybedford** [comment] 2015-09-22 19:38
Fixed in https://github.com/systemjs/builder/commit/5cf6d0e8768ad7c2bcd91f03f0465fb3d0a29cc8.

**Comment by SerkanSipahi** [comment] 2015-09-22 19:45
@guybedford "fixed pending release" for jspm 0.16.7 ?

**Comment by guybedford** [comment] 2015-09-22 21:19
Released in 0.14.4.

**Closed by guybedford** 2015-09-22 21:19 UTC
Labels: fixed pending release

**Comment by SerkanSipahi** [comment] 2015-09-23 08:00
@guybedford : after installing jspm 0.16.8 i get now a different error on `jspm bundle src/main dist/bundle.js --inject`:

```
     Building the bundle tree for src/main...

err  Error tracing npm:babel-runtime@5.8.24/core-js/object/define-property at file:///Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/extension-youtube/jspm_packages/npm/babel-runtime@5.8.24/core-js/object/define-property.js
	Error: Unable to calculate canonical name to bundle file:///Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/node_modules/core-js/library/fn/object/define-property.js
         at getCanonicalNamePlain (/Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/extension-youtube/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:177:13)
         at getCanonicalName (/Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/extension-youtube/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:88:19)
         at /Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/extension-youtube/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:305:32
         at process._tickCallback (node.js:356:9)
```

**Comment by guybedford** [comment] 2015-09-23 09:22
@SerkanSipahi yes that would be because it can't calculate the name to bundle `/node_modules/core-js/library/fn/object/define-property.js`. You need to ensure that that file path sits within the baseURL or a paths configuration so that jspm knows how to name it and refer to it equally between browser and server.

**Comment by SerkanSipahi** [comment] 2015-09-23 15:51
sorry @guybedford , before i used "jspm" i configured my System.config manually and bundled the apps over "Systemjs-Builder". That has always worked well. But now with jspm is something difficult, complicated, not clearly. What i want is just write an app( see problem https://github.com/systemjs/systemjs/issues/795 ) with jspm (it decreases a lot work).

// Folder-Structure
```
root
   | -- dist
   | -- src
   |    | - app.js
   |    | - core.js
   |    | - index.js
   |    | - main.js
   | -- package.json
   | -- manifest.json
```
 
// package.json
```json
{
  "name": "...",
  "version": "1.0.0",
  "description": "...",
  "scripts": {
    "test": "test"
  },
  "author": "Serkan Sipahi <serkan.sipahi@yahoo.de>",
  "license": "ISC",
  "devDependencies": {
    "jspm": "0.16.9"
  }
}
```

`npm install`
generate this:

// Folder-Structure
```
root
   | -- node_modules
   | -- dist
   | -- src
   |    | - app.js
   |    | - core.js
   |    | - index.js
   |    | - main.js
   | -- package.json
```

What now?

`user$ node_modules/.bin/jspm init`
```
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use a transpiler? [yes]:
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur? [babel]:
```

**Comment by guybedford** [comment] 2015-09-24 20:47
@SerkanSipahi your issue is simply that `file:///Users/serkansipahi/Dropbox/Works/Projects/vocabularytrainer/node_modules/core-js/library/fn/object/define-property.js` is not in jspm_packages it is in node_modules, so jspm can't bundle it. Somehow you must have told jspm to use that file.

**Comment by SerkanSipahi** [comment] 2015-09-25 18:19
@guybedford i told jspm nothing. Just use "jspm init" according wiki. No matter what I type in "jspm init" prompt, it makes no difference. Jspm produce always the same url in "jspm_packages/npm/babel-runtime@5.8.25/core-js/object/define-property.js":
 ```
root
   | -- node_modules
   | -- jspm_packages <---- 
   |    | - npm
   |    |   |- babel-runtime@5.8.25
   |    |      |- core-js
   |    |         |- object
   |    |         |- define-property.js
   | -- dist
   | -- src
   |    | - app.js
   |    | - core.js
   |    | - index.js
   |    | - main.js
   | -- package.json

/* */ 
module.exports = {
 /**
  * jspm try to require define-property.js outside from root !
  **/
  "default": require("../../../../../../node_modules/core-js/library/fn/object/define-property"),
  __esModule: true
};
```


This is what i do:
`cd root & node_modules/.bin/jspm init`

I tested several options:

```
Enter server baseURL (public folder path) [./]: /
Enter client baseURL (public folder URL) [/]: src
```
// or
```
Enter server baseURL (public folder path) [./]: ./
Enter client baseURL (public folder URL) [/]: /
```
// even
```
Enter server baseURL (public folder path) [./]: blabla
Enter client baseURL (public folder URL) [/]: blabla
```

????

**Comment by SerkanSipahi** [comment] 2015-09-25 20:24
This example https://github.com/jspm/jspm-cli/blob/master/docs/getting-started.md does not work if is any ES6 features in use e.g. class with method

Created everything according to instructions:
1. Install jspm CLI
2. Create a project
3. Install any packages from the jspm Registry, GitHub or npm
4. Write application code
5. Run the code
6. Bundle for production

```
root
   | -- node_modules
   | -- jspm_packages <---- 
   |    | - npm
   |    |   |- babel-runtime@5.8.25
   |    |      |- core-js
   |    |         |- object
   |    |         |- define-property.js ( try to load from  "require("../../../../../../node_modules/core-js/.........")
   | -- lib
   |    | - bootstrap.js
   |    | - main.js
   |    | - testclass.js
   | -- package.json
```

// bootstrap.js
```js
import _ from 'lodash-node/modern/lang/isEqual.js';
import $ from 'jquery';
import underscore from 'myname';
import testclass from './testclass'; // <= my testclass.js

export function bootstrap() {

}
```

// testclass.js
```js
export default class testclass {
    foo(){

    }
}

```

**Comment by guybedford** [comment] 2015-09-28 08:58
@SerkanSipahi this is definitely working fine for me. Are you running jspm 0.16.10 here? Also try running `jspm update -f babel babel-runtime` to ensure there isn't any cache issue.

**Comment by SerkanSipahi** [comment] 2015-09-28 17:35
@guybedford it does not make sense with  `jspm update -f babel babel-runtime` ! i get the same error. Yesterday i debug with node-inspector jspm but cant find the issue. Yes, its running jspm 0.16.10. 

Well, sorry, but i will give up with jspm. For me its better to use the old-school way => manually setting up system.js ( config.js) + systemjs-builder, that works fine :)

Thank you for your help. Maybe i will try next time jspm :)

**Comment by guybedford** [comment] 2015-09-28 19:45
Note that we use core-js as a separate package in jspm not the version nested inside of babel-runtime (whic your code seems to be running). It sounds like you have custom map configs that may be interfering with the jspm defaults somehow. If it's difficult to upgrade your config in this way certainly stick with plain SystemJS.

**Comment by SerkanSipahi** [comment] 2015-09-30 18:20
@guybedford i really want to resolve this issue !
1.) What you mean with "custom map configs" ! Which / What kind of -file do mean?
2.) When JSPM has nothing to do with the path, who makes => `require("../../../../../../node_modules/core-js/.........` ? babel? core-js?

**Comment by zloirock** [comment] 2015-09-30 18:44
@SerkanSipahi `core-js` does not uses `node_modules` directly.

**Comment by SerkanSipahi** [comment] 2015-10-03 09:23
@guybedford i deleted my global node_modules folder but even that did not help. Can you tell me which npm and node version do you use?

**Comment by guybedford** [comment] 2015-10-03 16:12
@SerkanSipahi the problem here is certainly that `require("../../../../../../node_modules/core-js/........` statement. If you can share with me any way to reproduce how you got that statement to show inside of babel-runtime on a fresh install I can help, but without the ability to replicate it's very difficult to know what to suggest here.

**Comment by SerkanSipahi** [comment] 2015-10-03 16:51
@guybedford I shared before. Here is what you want, a fresh install: https://github.com/SerkanSipahi/test-repo-jspm

**Comment by guybedford** [comment] 2015-10-03 17:13
@SerkanSipahi I tried that out already and had no problems. Perhaps share a repo with everything checked in if you can, and not containing a zip file?

**Comment by SerkanSipahi** [comment] 2015-10-03 17:30
@guybedford with "everything" inside `./jspm_packages` and `/node_modules after` installation?

**Comment by guybedford** [comment] 2015-10-03 18:02
Yes exactly!

**Comment by SerkanSipahi** [comment] 2015-10-03 18:06
@guybedford ok, this will take a some time because there are a lot of files !

**Comment by guybedford** [comment] 2015-10-03 18:24
@SerkanSipahi if you can reduce the test case to only the bare minimum number of files that is also a big help. Isolation and replication are the goals for issues / bugs.

**Comment by SerkanSipahi** [comment] 2015-10-03 18:26
@guybedford ok

**Comment by SerkanSipahi** [comment] 2015-10-06 09:57
sorry @guybedford, after our last talk i have reinstalled my mac because this issue has taken a lot of time. Well, now works everything fine with jspm. Many thanks for your help :)

**Comment by guybedford** [comment] 2015-10-06 12:18
@SerkanSipahi haha sure! Well glad to hear it's working.

**Comment by guybedford** [comment] 2015-10-06 12:49
@SerkanSipahi your issue actually turned out to be https://github.com/jspm/registry/issues/602.

**Comment by SerkanSipahi** [comment] 2015-10-06 12:53
@guybedford oh cool, seemingly you resolved it ?!?

**Comment by guybedford** [comment] 2015-10-06 12:53
Yes!

**Comment by SerkanSipahi** [comment] 2015-10-06 14:14
@guybedford good man :+1:
