### ISSUE TITLE
Getting deprecated option metadataUsedHelpers error

### ISSUE THREAD

**Issue by SonofNun15** [systemjs/builder#187] opened 2015-06-05 17:34 UTC
When building with the system building using babel:
```
	var builder = new Builder({
		baseURL: 'source',
		
		transpiler: 'babel',
	});
	
	builder.build('app.js', 'outfile.js').then(function() {
		console.log('Build complete');
		done();
	}).catch(function(err) {
		console.log('build error');
		console.log(err);
		done();	
	});
```
I'm getting the error: `Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default`

Any ideas on what is causing this and how to get past it?

**Comment by SonofNun15** [comment] 2015-06-05 17:38
Appears to be related to the latest version of babel-core, v5.5.3. When I install v5.4.7 of babel-core, this error goes away.

**Comment by SonofNun15** [comment] 2015-06-05 17:40
Listed here (https://babeljs.io/blog/2015/03/31/5.0.0/#breaking-changes) as a breaking change.

**Comment by guybedford** [comment] 2015-06-05 19:33
Thanks, closing as a duplicate of https://github.com/jspm/jspm-cli/issues/809.

**Closed by guybedford** 2015-06-05 19:33 UTC

**Comment by mikehaas763** [comment] 2015-06-09 15:54
This is now just a logged warning and the build actually works. However, the builder should now have a change to longer use `metadataUsedHelpers`, right?

**Comment by guybedford** [comment] 2015-06-09 16:22
Yes exactly, the builder will be updated here.

**Comment by dmackerman** [comment] 2015-07-31 14:43
I'm using `babel-core@5.8.19` and I'm still seeing this error.

**Comment by guybedford** [comment] 2015-08-02 11:13
@dmackerman how are you running the builder? Note that Babel is loaded as a module through SystemJS not Node, so the version that needs to be 5.8.19 is the version configured for SystemJS.

**Comment by dmackerman** [comment] 2015-08-03 16:13
@guybedford running it through the jspm CLI tool. JSPM 0.15.6.

**Comment by guybedford** [comment] 2015-08-06 14:34
@dmackerman and you're 100% sure `jspm inspect npm:babel-core` comes up as 5.8.19?

**Comment by dmackerman** [comment] 2015-08-07 13:24
Yep. 

```js
$ jspm inspect npm:babel-core

Installed versions of npm:babel-core

       babel 5.8.19 (^5.1.13)
```

**Comment by guybedford** [comment] 2015-08-08 11:19
@dmackerman if you can share a test case I can look into it.

**Comment by Quirksmode** [comment] 2015-10-26 18:22
I have the same issue with the following:

Installed versions of npm:babel-core

       babel 5.8.29 (^5.8.24)

**Comment by korto** [comment] 2015-10-27 16:05
Same here
`Installed versions of npm:babel-core`
`babel 5.8.25 (^5.1.13)`
`jspm -v`
`0.15.7`

**Comment by guybedford** [comment] 2015-10-27 16:54
Ah, thanks - fixed in https://github.com/systemjs/builder/commit/2ede3e99780f36590da16ace12aa89acf89ba21b. Apologies.

**Comment by korto** [comment] 2015-10-29 08:05
Thank _you_
