### ISSUE TITLE
Invalid sourcemap paths

### ISSUE THREAD

**Issue by Klaster1** [systemjs/builder#743] opened 2016-12-05 09:47 UTC
**My setup**:
- jspm@0.17.0-beta.32
- babel
- Windows 10

Vendor bundle:
`jspm bundle "app/desktop/main - [app/**/*.js] - [app/**/*!text] - [app/**/*.css!]" www/vendor.js`

App bundle:
`jspm bundle "app/desktop/main - vendor.js" www/desktop.js`

**What's wrong**:
Sources from **desktop.js.map** have wrong paths.

Expected:

	[  
	  "app/core/services/heartbeat.js",
	  "app/core/services/network.js",
	  "app/core/services/networkStatus.js",
	  "app/core/services/platform.js",
	  "app/core/services/customField.js",
	  "app/core/services/widgets.js",
	  "app/core/services/focus.js",
	  "app/core/services/symbols.js",
	  "app/core/services/auth.js",
	  "app/core/branding/branding.json",
	  "app/core/services/branding.js",
	  "app/core/services/users.js",
	  "app/core/services/symbolSubscribe.js",
	  "app/core/services/strategies.js",
	  "app/core/services/strategyParams.js",
	  "app/core/services/strategyTypes.js",
	  "app/core/services/trader.js",
	  "app/core/services/quotes.js",
	  "app/core/services/quotes2.js",
	  "app/core/services/trades.js",
	  "app/core/services/alerts.js",
	  "app/core/services/sound.js
_... and a lot more._

Actual:

	[  
	  "component.js",
	  "WidgetSettingsDialog.js",
	  "SymbolInfoDialog.js",
	  "GeneralSettingsDialog.js",
	  "notificationPopup.js",
	  "WorkspacesManagementDialog.js",
	  "AddWorkspaceDialog.js",
	  "main.js",
	  "config.js",
	  "controller.js",
	  "dialog.js",
	  "directive.js",
	  "connectionStatusComponent.js",
	  "popoverDirective.js",
	  "service.js",
	  "reactgrid.js",
	  "jspanel.js"
	]

As you can see, all paths are not paths at all, but file names. This causes wrong sources tree in Chrome inspector and files with same name are merged. Interestengly, **vendor.css.map** sources don't have this issue.

After lurking issues for some time, I've singled out #715 as a root cause. Reverting [condition](https://github.com/systemjs/builder/pull/715/commits/cec7843542ec2d02eb92945de9d79421aa48f206) from that pull-request back to `if (output.map)` fixes sourcemap sources.

**Comment by guybedford** [comment] 2016-12-09 13:44
@Klaster1 thanks for tracking this down. I'm happy to revert #715 if that is the best way forward here.

**Comment by Klaster1** [comment] 2016-12-12 14:24
@guybedford I'd certainly appreciate the rollback, but I'm not sure about @laurentgoudet from #715. Perhaps you can figure a fix that addresses both issues?

**Comment by alexisvincent** [comment] 2016-12-13 14:24
@guybedford I can confirm that reverting #715 will fix my issue as well

**Comment by laurentgoudet** [comment] 2016-12-13 14:47
The issue is that `output.map` is different whether `rollup` is enabled or not.

When Rollup is used, the `sources` list contains the proper paths, and no workaround is needed (and `output.map.sources[0] = load.path;` would set the path to the wrong source file):

```
{ version: 3,
  file: null,
  sources:
   [ 'modules/@shared/translation/index.js',
     'modules/@shared/url/index.js',
     'modules/@shared/cookie/index.js',
     'modules/@shared/email-validation/index.js',
     'modules/about-careers/index.js' ],
  sourcesContent:
   [ 'import _ from \'underscore\'...' ],
  names: [],
  mappings: ';;;;;AAEO,WAAA,GAA....' }
````

When Rollup is not used, even with `buildStatic`, `output.map` contains a single file and the path is invalid :

```
{ version: 3,
  sources: [ 'index.js' ],
  names:
   [ '$',
     'T_',
     ...
     'resetForm' ],
  mappings: ';;;;;;AA2IA,WAAA,AAAS,',
  file: 'index.js',
  sourcesContent: [ 'import $ from \'jquery\';\' ] }
```

However, `load.metadata.sourceMap` already contains an invalid path. No idea where that initial sourceMap comes from (`traceExpression`?). A hack could be to use `output.map.sources.length === 0` in the conditional but investigating & fixing the root cause might be preferable.

**Comment by alexisvincent** [comment] 2017-01-08 09:40
@guybedford Can we please revert #715

**Comment by asapach** [comment] 2017-01-09 10:29
@alexisvincent do you have a repro case? This might have been fixed by systemjs/plugin-babel#71

**Comment by alexisvincent** [comment] 2017-01-09 10:32
Oh cool. Will have to test. Unfourtunately 0.0.18 is broken for me because of an issue with generator functions. But will verify if 0.0.18 fixes things for me.

**Comment by guybedford** [comment] 2017-01-13 11:44
@alexisvincent let me know if this works out for you.

**Comment by alexisvincent** [comment] 2017-01-13 11:45
Will check later today.

**Closed** 2017-01-25 08:40 UTC
