### ISSUE TITLE
rollup doesn't work together with source-map-contents

### ISSUE THREAD

**Issue by sormy** [systemjs/builder#719] opened 2016-10-19 00:37 UTC
systemjs-builder@0.15.32

example: https://github.com/sormy/jspm-hot-skeleton
How to reproduce: remove `--skip-rollup` from `package.json` and try to run `npm run build:dev`

Error: Mismatched sourcesContent

**Comment by asapach** [comment] 2016-10-19 09:15
This has been fixed in #715. Pending release.

**Comment by guybedford** [comment] 2016-10-19 13:03
Marking as a duplicate of https://github.com/systemjs/builder/issues/678.

**Closed by guybedford** 2016-10-19 13:03 UTC
