### ISSUE TITLE
__moduleName is empty (undefined)

### ISSUE THREAD

**Issue by acostaf** [systemjs/builder#635] opened 2016-06-27 15:50 UTC
HI Team

buildStatic js using systemjs set __moduleName as empty, I have already used encodeNames: false but nothing

**Comment by guybedford** [comment] 2016-06-27 16:37
Does it work when dynamically loading?

If so what transpiler configuration are you using?

**Comment by acostaf** [comment] 2016-06-27 17:09
Hi Guy

I am transpiling from Typescript (module:system) everything works file untill I bundling using systemjs.builder

**Comment by guybedford** [comment] 2016-06-27 18:20
__moduleName builds are only supported as of TypeScript 1.8, make sure you are using at least that version? Also __moduleName is only supported for ES modules.

**Comment by acostaf** [comment] 2016-06-28 07:50
Hi Guy 

__moduleName works fine during development systemjs fill it with the right data the issue is when I package the javascript files with systemjs bulder, then the value is empty, as I said before I used **encodeNames: false** to prevent the name to by mangled up but not luck.

Any idea?

**Comment by guybedford** [comment] 2016-06-29 10:06
As mentioned, this is determined by the system you use to build your JS, _even if it did work in the browser_. I'd suggest checking your transpilation options and confirming that it is a system module format output on TypeScript 1.8 or greater.

**Comment by Jefftopia** [comment] 2016-07-20 19:48
@acostaf @guybedford Same issue. I'm using typescript 1.8.10. I had to revert transpilation to commonjs and module.id until the issue is resolved.

**Comment by asapach** [comment] 2016-07-20 19:51
Do you guys have a repro case? Builder should handle `__moduleName` when you use `System.register()` format.

**Comment by frederikschubert** [comment] 2016-07-26 05:19
[This](https://github.com/systemjs/builder/commit/cb94933ecf504f9069f9437d53d3c0c7193c5148) should fix it.

**Comment by guybedford** [comment] 2016-07-26 12:28
Yes this was a bug in SFX... fix coming in this release.

**Comment by guybedford** [comment] 2016-07-26 13:03
Released in 0.15.24.

**Closed by guybedford** 2016-07-26 13:03 UTC
Labels: fixed pending release
