### ISSUE TITLE
npm package should not include tests

### ISSUE THREAD

**Issue by rivertam** [systemjs/builder#703] opened 2016-09-29 22:51 UTC
NPM package currently contains tests, which are not useful for consumers of the library or (like me) consumers of libraries that depend eventually on this library. =)

**Comment by asapach** [comment] 2016-09-29 23:10
Duplicate of #696 and should have been fixed already in 0.15.32 by e32ffb36f5e73ccedee52b465d08015f3baf1a10

**Closed** 2016-10-25 13:12 UTC
