### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by JockVanDallas** [systemjs/builder#674] opened 2016-08-24 12:31 UTC
Hi

Today i got this error message "Uncaught ReferenceError: System is not defined" after creating a sfx bundle with jspm. Two weeks ago everything still worked when i did this
```
jspm bundle-sfx main.js main.bundle.js
```
When looking in the non minified code of the bundle i see
```
$__System.registerDynamic('58', ['57'], true, function ($__require, exports, module) {
  var define,
      global = this || self,
      GLOBAL = global;
  module.exports = System._nodeRequire ? process : $__require('57');
  return module.exports;
});
```
This is the only place where System is used instead of $__System.
When i replace **System** with **$__System** everything works fine.

I saw some other issues with almost the same issue, but those did not help me 

Using these versions of npm, node and jspm
```
bash-3.2$ npm -v
3.5.3
bash-3.2$ node -v
v5.4.0
bash-3.2$ jspm -v
0.16.44
Running against local jspm install.
```

**Comment by guybedford** [comment] 2016-08-24 14:57
Marking as a duplicate of #673.

**Closed by guybedford** 2016-08-24 14:57 UTC
