### ISSUE TITLE
new Builder('configPath')

### ISSUE THREAD

**Issue by MeoMix** [systemjs/builder#303] opened 2015-09-07 00:03 UTC
Hey,

I had this code:

    var builder = new Builder();
    builder.loadConfigSync('config.js');

I was looking through the source code and realized I should be able to do:

    var builder = new Builder('config.js');

However, this doesn't work as expected. I need to do:

    var builder = new Builder(undefined, 'config.js');

Do you think the shorter syntax could be supported?

**Comment by guybedford** [comment] 2015-09-08 16:16
The issue is that we take a baseURL argument into the builder, which is also a string argument.

At the moment the `baseURL` constructor argument seems more important than the config file one.

Also bear in mind that `config.js` needs to have a baseURL provided to be interpreted correctly here anyway, so two arguments should always be necessary.

**Comment by guybedford** [comment] 2015-09-08 16:16
That said, if you can suggest something neater, I'm happy to consider it.

**Comment by guybedford** [comment] 2015-09-11 16:38
Closing as I think a `baseURL` should always be provided, even if it is just `.`.

**Closed by guybedford** 2015-09-11 16:38 UTC

**Comment by MeoMix** [comment] 2015-09-19 22:42
Hey,

Looking at the source for builder -- it looks like if I provide both a baseURL and a config which contains a baseURL then my given baseURL is not respected.

That feels incorrect to me. Is it intentional?

I feel like if I give a baseURL when creating the builder then that should override a baseURL referenced in the config.
